name: recipe_api
description: The interface and models for an API providing access to recipe.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cloud_firestore: ^4.0.3
  equatable: ^2.0.3
  json_annotation: ^4.6.0
  # meta: ^1.7.0
  # rxdart: ^0.27.5
  # shared_preferences: ^0.5.5
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  test: ^1.21.4
  very_good_analysis: ^3.0.2